
services:
  hotel-service:
    build:
      context: ./services/hotel-service

    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
 